pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('trivy folder scan'){
            steps{
                sh '''
                    /bin/trivy fs . > trivy_fs_report.txt
                '''
            }
        }
        stage('docker build'){
            steps{
                sh 'docker build -t surya22ganesh/tettrisgame .'
            }
        }
        stage('trivy image scan'){
            steps{
                sh '/bin/trivy image surya22ganesh/tettrisgame > trivy_image_report.txt'
            }
        }
        stage('docker image push'){
            steps{
                // withDockerRegistry([credentialsId: 'docker', url: 'https://hub.docker.com']) {
                    sh '''
                        docker login -u surya22ganesh -p Surya@1999
                        docker push surya22ganesh/tettrisgame
                    '''
                // }
            }
        }
        stage('trivvy image scan'){
            steps{
                sh 'trivy image surya22ganesh/tettrisgame > trivy_image.txt'
            }
        }
        stage('updating deployment.yaml file'){
            steps{
                git branch: 'main', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/surya22ganesh/surya-tetris-deployment-file.git'
            }
        }
    }
}
